### ISSUE TITLE
Allure-reporter. Modify TmsLink to use TC ID and not TC name

### ISSUE THREAD

**Issue by olgapuig** [systelab/allure-reporter#11]

**Comment by orozluk** [comment]
Using the Jama Test Case Key value would make more sense, than using the Jama Test Case Name to uniquely identify and match an Allure Test Case and a Jama Test Case.

**Comment by ManelMoreno** [comment]
After the Jorge's fix, we need to fully test this feature (both by ID and by Name), and evaluate how to solve the impact in the Title Name that is shown in Allure Report (using TC ID to match JAMA TC, avoids the Test Case name in the report, which should keep appearing). Should we open a new issue to manage this afectation?

**Comment by ManelMoreno** [comment]
This implementation is to be verified. Please add here the cases tested and the results.

**Comment by ainhoam** [comment]
Two test cases created in jame, ones to upload by TC name and other to upload by TC id.
Two test cycle created, ones for json files and other to Json format.

**Both upload as expected:**
![TestRunUploadbyxml](https://user-images.githubusercontent.com/2478494/76310025-4a722100-62ce-11ea-9544-4fba4538267b.PNG)
![TestRunUploadbyjson](https://user-images.githubusercontent.com/2478494/76310026-4b0ab780-62ce-11ea-969b-a52888a5bc11.PNG)

**Files:**
[FilesToVerifyUploadTestRunByID.zip](https://github.com/systelab/allure-reporter/files/4312268/FilesToVerifyUploadTestRunByID.zip)

**Evidences:**
[Evidencia TC by Id Allure Reporter V2.pdf](https://github.com/systelab/allure-reporter/files/4312283/Evidencia.TC.by.Id.Allure.Reporter.V2.pdf)
[[xml files]Evidencia TC by Id Allure Reporter V2.pdf](https://github.com/systelab/allure-reporter/files/4312284/xml.files.Evidencia.TC.by.Id.Allure.Reporter.V2.pdf)

**Comment by ManelMoreno** [comment]
Ok, thanks Ainhoa!
Just to point for that the executions in JAMA for XML files could be notice that XML files are used instead of json, as Test Preconditions and steps refer alwyas to json files..
