### ISSUE TITLE
'Report to Jama' dialog is displayed when transfer cannot be made

### ISSUE THREAD

**Issue by atzurk** [systelab/allure-reporter#17]
When trying to connect to Jama for transfer the report, if the configured user is **not found in Jama**, or the Jama server **is down**, the 'Report to Jama' **dialog shouldn't be displayed**, as no transfer can be made wihtout correct Jama user nor Jama server down.

**Comment by olgapuig** [comment]
Do not enable the "Report to Jama" until the user is properly logged.
Display a message popup with the error that the Api returns

**Comment by olgapuig** [comment]
The final solution is to display the error that is returned by the Rest API by clicking on the Submit button in the Login dialog. Cases:

- When the user or the password is not right, the Rest API returns the message "wrong username or password" with code 401. See dialog below ![image](https://user-images.githubusercontent.com/1970034/128498465-45d91f40-b590-473c-9aa4-f0fb10845f22.png)

- When the server is not found, 401 is the response. ![image](https://user-images.githubusercontent.com/1970034/128498915-0225bde6-c092-4000-a26f-ac551d268a92.png)
- When the server is found but the Rest API access is not right, "Network error occurred" ![image](https://user-images.githubusercontent.com/1970034/128499388-1130ec9b-141f-487f-ba45-492a9df3881d.png)

In the previous cases, the upload button to Jama will be disabled.

**Comment by JordiCela** [comment]
Issue has been verified and **PASSED**.
An exploratory Test has been done.
See the following attached document 'TEST ALLURE-REPORTER v.3.0 (ISSUE #17).docx' for details of the Test:



See the following attached file to see the Evidences of the Test:
