### ISSUE TITLE
Test Group ComboBox disabled when configuring Jama connection

### ISSUE THREAD

**Issue by atzurk** [systelab/allure-reporter#18]
When trying to connect to jama and transfer the report information, the test group combo gets disabled and no selection can be done. If we click on Report an error message is displayed and no information is sent to jama. (tested in version 1.0)

![image](https://user-images.githubusercontent.com/39374121/45484952-2e7fd480-b756-11e8-965f-308104eb7ee2.png)

**Comment by alfonsserra** [comment]
The Test Group can be selected only if you create a New Cycle.
