### ISSUE TITLE
The steps (@Test, the first level) must be displayed in the same order as executed

### ISSUE THREAD

**Issue by olgapuig** [systelab/allure-reporter#22]
The steps (@Test, the first level) must be alphabetically ordered inside each Test Case (@tmslink)
It would be better to also order alphabetically the Test Cases inside a suite.

**Comment by danipiques** [comment]
From my point of view we have to find a different solution better than order them alphabetically. The alphabetically order is not maintainable

**Comment by olgapuig** [comment]
Fixed in #34.  The solution is to use the "start" field to display them in the same order as executed.
