### ISSUE TITLE
Support titles within steps

### ISSUE THREAD

**Issue by olgapuig** [systelab/allure-reporter#24]

**Comment by apariciojl17** [comment]
![image](https://user-images.githubusercontent.com/20879685/47426926-05a82180-d78f-11e8-9510-d7d2e825c318.png)

**Comment by JordiCela** [comment]
This issue also happens to me.

**Comment by ManelMoreno** [comment]
I need to understand better this CR.

**Comment by olgapuig** [comment]
This feature is requested by other projects with the purpose of adding titles as steps.
![image](https://user-images.githubusercontent.com/1970034/71906739-f5e5e480-316a-11ea-9ae6-a8559681ea6d.png)

**Comment by ManelMoreno** [comment]
I would Reject this request. The motivation seems to be based in an old limitation of this tool.

**Comment by ManelMoreno** [comment]
I would Reject this request. The motivation seems to be based in an old limitation of this tool.
