### ISSUE TITLE
Show on the report some labels present on the .xml file (build, user, executionDate)

### ISSUE THREAD

**Issue by apariciojl17** [systelab/allure-reporter#27]
There are some labels present on the .xml file that may appear on the top (or bottom) of the report.

As they appear on the .xml file:

label name='appBeingTested' value='laboratory'
abel name='appName' value='Modulab'
label name='appDescription' value='Laboratorio'
label name='appVersion' value='Versión: 3.1.03 (build 1)'
label name='testVersion' value='0.8.0'
label name='testCreatedBy' value='name@domain.com'
label name='testLastModifiedBy' value='name@domain.com'
label name='testStartedAt' value='OCT/24/2018 13:28:53'
label name='company' value='company_name'
label name='browserName' value='chrome'
label name='browserVersion' value='70.0.3538.67'
label name='platform' value='Windows NT'

Developed solution:
- All the labels are displayed except from 'tms', 'feature', 'suite' and 'package'. The intended use of this feature is to include the tester, execution date, build and browsers.

**Comment by olgapuig** [comment]
![image](https://user-images.githubusercontent.com/1970034/52292992-28dd9200-2976-11e9-9065-ea1ed82cd348.png)
