### ISSUE TITLE
WordWrap

### ISSUE THREAD

**Issue by apariciojl17** [systelab/allure-reporter#37]
When some long words are included, for example, in the column "Expected result" (it may happen ih the rest of the columns too), the app doesn't do the wrap and the remaining text are shown all over the next rightest columns. Please see attached files and the proposed solution that was tested in Edge v42.17134, Chrome v72.0, Firefox v65.0 and Opera v58.0.

![wordwrap_issue](https://user-images.githubusercontent.com/20879685/54356442-ea658200-465b-11e9-9b1b-a61b2445ec91.png)

**Comment by olgapuig** [comment]
Done in V1.0
