### ISSUE TITLE
The link to a Test Case example is broken in main page

### ISSUE THREAD

**Issue by atzurk** [systelab/allure-reporter#39]
**Describe the bug**
The link in the main page to an example of how to write a Test Case is not working now, because it points to a non-existing file.

**To Reproduce**
1. Go to main screen, at the bottom.
2. Click on: See the example at "login.e2e-spec.ts" (here)
the link leads to a not-found page.

**Expected behavior**
The page of the file that is supposed to be displayed:
https://github.com/systelab/seed-angular/blob/master/e2e/login/login.e2e-spec.ts

**Comment by JordiCela** [comment]
This issue still happens in version 2.0.0 and version 3.0.0

**Comment by olgapuig** [comment]
The seed-angular was updated to use WDIO and the new link is https://github.com/systelab/seed-angular/blob/master/e2e-wdio/tests/login.e2e-spec.ts

**Comment by ManelMoreno** [comment]
Tested in v.3.0
