### ISSUE TITLE
Update Test Case in Jama: Steps and Description

### ISSUE THREAD

**Issue by danipiques** [systelab/allure-reporter#40]
Currently, when we execute a test case and report to JAMA via allure, there is a field "Actual Result" which contains a table with the Java Function and the Test Description.

Different people has reported that this is not clear because is not the typicall test case format. The interestant thing should be store the test case executed. Options:

1) Store in the Actual Results the Test Description and the Expected Results (Easier)
2) Store in the Steps table of the Test Run AND the Test Case the Description and the Expected Results (Preferred).

NOTE: With the second option we should consider projects that are writing the steps manually because an automatic execution could modify the steps introduced manually

**Comment by ManelMoreno** [comment]
Dani, the Test Run upload can not modify the Steps table, as Test Runs are a snapshot of the TC in the moment of creating/editing a Cycle

**Comment by ManelMoreno** [comment]
This issue refers to the synchroniztion between steps in allure reporter and JAMA.
We have created a new issue referred to the content of 'Actual Results' See [https://github.com/systelab/allure-reporter/issues/46](url).

**Comment by olgapuig** [comment]
The Test Case can be updated using the Jama Api as follows:

1.  GET /abstractitems 
Use the filter "contains" with the Test Case Name
Get the id from the data ("data": [{"id": 509244,)

2. GET /items/{id}

3. PUT /items/{id} 
Update the steps in the Test Case though the field "testCaseSteps"
Example: 
{
  "globalId": "895528",
  "project": 39,
  "itemType": 26,
  "childItemType": 0,
 "location": {
      "sortOrder": 0,
      "globalSortOrder": 1960762029,
      "sequence": "2.2.1",
      "parent": {
        "item": 508062
      }
    },
    "fields": {
      "name": "TBD1",
      "globalId": "895528",
      "documentKey": "SEED-TC-21",
      "description": "",
      "testCaseSteps": [
        {
          "action": "Execute TBD1",
          "expectedResult": "Each step meets the expected result",
          "notes": ""
        },
        {
          "action": "Step 2 ",
          "expectedResult": "Expected result 2",
          "notes": ""
        }
		,
        {
          "action": "Step 3 ",
          "expectedResult": "Expected result 3",
          "notes": ""
        }
      ],
      "tc_type$26": [
        460
      ],
      "priority": 281,
      "testCaseStatus": "SCHEDULED",
      "release": 407,
      "test_design_status$26": 464,
      "status": 291
    }
}

**Comment by ManelMoreno** [comment]
We need to evaluate the impact of this request. Changes in TCs (or steps in TCs) from Allure, could affect existing approved reviews of the TC or pending updates of the design.

**Comment by olgapuig** [comment]
Proposed solution: 
- Add the option to "Update Test Case Steps". By default it is unselected.
- The Test Case must be updated before updating the Test Runs in Jama
![allure_reporter_issue40_proposal](https://user-images.githubusercontent.com/1970034/72627679-37397980-394d-11ea-9857-ec17bc9dbfc9.png)

**Comment by olgapuig** [comment]
Solution:
- New button "Update Test Case Steps" to automatically synchronize the steps in the Test Case in Jama. The required parameter is just the project.
![image](https://user-images.githubusercontent.com/1970034/73068895-a31b6500-3eac-11ea-859e-b2b1e69e6ce0.png)
- It considers the 2 Test Cases item types (CSW and IL) defined at Jama
- The Steps table must be the same as in Allure-reporter 
Example:
![image](https://user-images.githubusercontent.com/1970034/73068964-d5c55d80-3eac-11ea-87b5-01cea4a03e28.png)
![image](https://user-images.githubusercontent.com/1970034/73069016-f097d200-3eac-11ea-908c-ea4fb9576105.png)
![image](https://user-images.githubusercontent.com/1970034/73069050-06a59280-3ead-11ea-8d50-6264458c3a1d.png)

**Comment by ManelMoreno** [comment]
The implemented solution allows the update of TC definition in an action independent from the Report of results. This will allow to update TCs, perform actions like review and approval, and then Report the results un a subsequent action. 
@olgapuig take also into account the TC item type that Snow is being using on the Snow-JAMA instance, that is different from the CSW one.

**Comment by ehilinger** [comment]
Tested against FactorXIV JAMA project.
- Created 2 copies of existing test cases:
MLG_TC1208_API_REST_Study
Error Handling
- Created fake test plan and cycles

1 - Upload test and results
It is possible to update test and upload results but there is a consideration.
Once test is updated, as it is already in a cycle it is needed to "Make test case as current" to update test case in the cycle before uploading the results.

2 - Update test:
Multi line description: It is possible to upload a multi line description
Update test case removing steps: Test case is updated successfully with less steps
Update test case adding steps: Test case is updated successfully with more steps
Update step description: It is possible to update step description
