### ISSUE TITLE
Document the mapping model from allure-json to allure-reporter model to JAMA

### ISSUE THREAD

**Issue by orozluk** [systelab/allure-reporter#45]
In order to facilitiate the troubleshooting and customization of non-java-generated json files it would be nice to have a mapping table where the map between allure-json model and allure-reporter internal model is cleary shown, including _special assumptions_ like `Action:` prefix in step names (and what they do). That would help a lot when customizing the report to what is intended. 

And, if a map from the allure-reporter to JAMA exists, that will be great!

**Comment by ManelMoreno** [comment]
Great idea, very useful for C#, C++ and Angular (TS) implementations.
Here Ainhoa started something that can be the seed for what you request.
https://github.com/systelab/allure-reporter/blob/master/src/assets/dotnet.md

Let's share and find interested people.

**Comment by ManelMoreno** [comment]
Olga created a first version of this table in:
https://jira.ilww.com:8099/confluence/pages/viewpage.action?pageId=97488456

Let's review it and merge if needed with the one created by Ainhoa.

**Comment by ManelMoreno** [comment]
Completed my reviewed and update of the content (in Confluence, Olga updated it by PR to have it documented in the same Allure Reported tool. 
Please, the rest, review it and update if needed. 
If nobody comments, we can close it in 2 weeks.

**Comment by olgapuig** [comment]
The Test Case description and steps (actions and expected results) can be synchronized with Jama (#40). It's already documented in the mapping model.

**Comment by ManelMoreno** [comment]
@orozluk , please let me know when your needed update is ready to be reviewed and the Closed.

**Comment by ManelMoreno** [comment]
@orozluk Jorge, could we Close this item?

**Comment by orozluk** [comment]
Yes, it can be closed. Thanks
