### ISSUE TITLE
Re-define the use of 'Actual Results' information

### ISSUE THREAD

**Issue by ManelMoreno** [systelab/allure-reporter#46]
It is needed to re-define what information do we want to be uploaded with Test Runs to 'Actual Results' field in JAMA.

1. Review current info being uploaded.
2. Provide ways to include Location of Test Evidences (logs, allure report containing input&output data, db, screenshots, etc.)
3. Provide ways to include Test Environment used

This is for each Test Run

**Comment by ManelMoreno** [comment]
After the meeting with Olga, Dani, Ainhoa and myself, these are the actions derived (please modify with your comments/considerations):

1. Remove the current content of 'Actual Results' (stop setting the table with the class/function name and Action)
2. Automated Test Run must have information related to:
 - **Test Environment used to run the Test Case.** 
    Could be:

     - a static text indicating that the detailed in JAMA test plan have been followed,
     - or that is detailed in the same Allure Report (indicated where it is)
     - explicit detail of Envir.used (HW/SW/SN/Configuration/DBs/Tools/etc..)

 - **Indication where Evidences are located** (mandatory for Medical Devices, optional/wished for the rest). Could be a sentence like: "See Test Execution evidences in: \\sltrep\...xxx". Allure report is a mandatory evidence of automation execution and must contain the specific values used for testing.

 - To satisfy the requirement of filling the result for each step, Actual Results could also contain the text:  "Executed all steps with results as expected", for PASS status.

**Comment by olgapuig** [comment]
Potential solution:
•	Add the new field “Actual Results” as Text Area in the form to upload results to Jama
•	Add a new label “Actual Results” to the JSON/XML that automatically updates the Actual Results field in the Test Run in Jama. This information will be automatically added to the Test Run in Allure. The Test Design does not include this information.
•	When the “Actual Results” is informed in the JSON/XML, the information entered into the “Actual Results” in the UI must be concatenated.

**Comment by ManelMoreno** [comment]
We(Olga, Susana &Manel) met on 11/12/2019 and decided the solution to be implemented (see details above) mainly based in the proposals.
The content of field 'Actual Results in JAMA will be filled by either a label in JSON/XML and/or A new free text in the Allure Report UI. No more input sources. Current table will not more appear.
All the labels informed in the code (and so in JSON) will appear in Allure report for each Test Run.
This should be enough to allow any project to report without manual effort all the required information to formalize automated TCs in Jama.

About Executed in version, we decide a new way to report ir. See more info in a different issue ().

**Comment by olgapuig** [comment]
Final solution:

- Add the new field “Actual Results” as Text Area in the form to upload results to Jama. Increase the dialog size to fit all the content. Refer to ![image](https://user-images.githubusercontent.com/1970034/71193138-e79e5a00-2289-11ea-826d-a014cb227232.png)
- Add a new label “Actual Results” to the JSON/XML that automatically updates the Actual Results field in the Test Run in Jama. This information will be automatically added to the Test Run in Allure. Refer to ![image](https://user-images.githubusercontent.com/1970034/71193195-013fa180-228a-11ea-914e-2973e05beaff.png) and 
![image](https://user-images.githubusercontent.com/1970034/71193208-07358280-228a-11ea-8598-507c9479c487.png)

- The Test Design does not include this information. Hide all the execution information (labels and actualResults) when the Test Design is displayed. Refer to 
![image](https://user-images.githubusercontent.com/1970034/71193251-174d6200-228a-11ea-91a7-1c5f0155b5e5.png) and 
![image](https://user-images.githubusercontent.com/1970034/71193263-1caaac80-228a-11ea-8dcc-ba529f354eeb.png)

- When the “Actual Results” is informed in the JSON/XML, the information entered into the “Actual Results” in the UI must be concatenated.

- Remove the previous content from the ActualResults in Jama and use the new one.

**Comment by ManelMoreno** [comment]
Great Olga! Do we have it deployed in order to make some test?

**Comment by olgapuig** [comment]
Yes, it’s automatically deployed at the test environment when a Pull-request is performed. Refer at  https://systelab.github.io/allure-reporter-test/.
There’s still a minor change to develop, which is to have a proper display in Jama when it’s a multi-line text considering the line-breaks.

**Comment by ManelMoreno** [comment]
This implementation is to be verified. Please add here the cases tested and the results.

**Comment by ManelMoreno** [comment]
Verification done, no problems found except cosmetics (one of them fixed in an internal cycle.
Verified several cases described in the attached file using XMLs and JSON, reporting Actual Results texts from the files and/or from UI (new field added into Allure Reporter UI form)

**Comment by ManelMoreno** [comment]
@SCoboG : please review the verification done and move it to Close status.

**Comment by ManelMoreno** [comment]
This feature has already been used by other test members in Synapse and QL4 projects, so I can consider it validated.
