### ISSUE TITLE
Reporting of 'Executed in version' value for Test Runs

### ISSUE THREAD

**Issue by ManelMoreno** [systelab/allure-reporter#51]
This request is related to issue #46 and is referred to the management of the value of 'Executed in version'.

The value of the version where the automatic TC is executed is currently being reported using the Test Cycle name. Recently I faced projects not using it, so this mandatory information is not being set. So we met and decide a best way to report this value:

  - JAMA will have a new field for Test Run item called 'Executed in Version'. This field will contain the list of Releases that each project have in JAMA.

  - Allure Reporter UI will contain a new field [Radio-button selection] to support the setting of this value, deciding if Releases from Jama have to be used or using the already set 'New Cycle Name'(avoiding its repetition):
           "Executed in Version (Test Run):
               o Release: combo Releases (X.Y.Z b)
               o Use New Test Cycle name"

**!** Olga: this proposal will not work if I set in JAMA that values will come just from Releases list, if Cycle Name set is not exactly a value in the list**!**

Having this field is also a current need for Traceability matrix building.

**Comment by olgapuig** [comment]
The Release field only contains the major release versions for some projects.
This feature must be optional

**Comment by ManelMoreno** [comment]
Just to clarify, if the Radio-button selection is not clear or easy to implement (I have some doubts about the match of Cycle Name with exact values of Release), the need is covered by adding and optional combo called "Executed in Version", where the user can set the 'Release' value coming from JAMA project selected.

**Comment by ManelMoreno** [comment]
Derived from this issue, the team proposed to upload also the same value to the field 'Last Executed version' of the Test Case item corresponding to each Test Run. I will be in charge of the evaluation of this proposal and will open a new issue.
In any case, the implementation of this one must take into account both issues.

**Comment by ainhoam** [comment]
The field "tested in version" is upload.
![testInVersionILTC](https://user-images.githubusercontent.com/2478494/188559310-796281b9-6db1-46cb-ba19-3166919f06f9.png)
