### ISSUE TITLE
User uplading results to JAMA needs more feedback about upload done ('Report' button).

### ISSUE THREAD

**Issue by ManelMoreno** [systelab/allure-reporter#53]
When users upload results to JAMA (using 'Report' button) they needed to receive feedback about:
- Upload is in progress
 - Upload has finished (all Test Runs have been uploaded)
 - How many Test Runs have been uploaded and how many were not (if possible provide information about the failure cause: TC not found / matched; communication failure; Wrong content....)

**Comment by joaquimvila** [comment]
+1

**Comment by ManelMoreno** [comment]
A new issue has been created to split the same request about feedback, for 'Report' action (this same issue #53) and for 'Update Test Case' action: #72)

**Comment by ManelMoreno** [comment]
If #73 is also implemented, there is a suggestion to include feedback about Test Cases modification (in some manner, p.ex: quantity)

**Comment by olgapuig** [comment]
The upload can be detailed as follows:
-	Number of Test Runs with Pass status
-	Number of Test Runs with Failed status
-	Number of Test Runs that exist in Jama but are not updated
-	Number of Test Runs that does not exist in Test Groups in Jama
-	Total of Test Runs to upload

**Comment by OscarDeDios** [comment]
Solution proposed in the PR:

![image](https://user-images.githubusercontent.com/722614/132735935-c8920425-05c2-4c13-a8ed-a27e9ce0fa7b.png)



https://user-images.githubusercontent.com/722614/132667747-fa51dd9d-ec93-4e06-836e-adc54c6b00e0.mp4

**Comment by SCoboG** [comment]
Defect retested with an exploratory Test. The result of the testing has been **FAIL**
**--> The failure is becuase the list of items not found is not accurate in some case**

See the following attached document:
- Exploratory Test item #53.txt  
- Evidences item #53.zip
[Exploratory Test item #53.txt](https://github.com/systelab/allure-reporter/files/8580359/Exploratory.Test.item.53.txt)
[Evidences item #53.zip](https://github.com/systelab/allure-reporter/files/8580360/Evidences.item.53.zip)

**Comment by olgapuig** [comment]
Fix: Test Cases with Failed status are not considered in the Wrong Uploads section

**Comment by SCoboG** [comment]
Defect retested with an exploratory Test. The result of the testing has been PASS

See the following attached document:
- Scenarios Under Test [scenariosUnderTest.zip](https://github.com/systelab/allure-reporter/files/9671693/scenariosUnderTest.zip)
- Evidences [Evidences.zip](https://github.com/systelab/allure-reporter/files/9671692/Evidences.zip)
