### ISSUE TITLE
Inform about the Failed Step when allure-js is in use

### ISSUE THREAD

**Issue by olgapuig** [systelab/allure-reporter#54]
**Is your feature request related to a problem? Please describe.**
When there's a Failed step, the whole Test Case is reported as Failed without indicating the step that fails. It only happens with XML and works properly with JSON formats.

Scenario:
XML file --> [TC_failed_xml_allure1.txt](https://github.com/systelab/allure-reporter/files/4076980/TC_failed_xml_allure1.txt)
Report in allure --> ![image](https://user-images.githubusercontent.com/1970034/72615564-562c1180-3935-11ea-970c-4ef84037c93c.png)

**Describe the solution you'd like**
Display as "Failed" with a red cross the failed step. Given the failed information is only at step level, all the expected results rows will have the red cross.
![image](https://user-images.githubusercontent.com/1970034/72615809-cf2b6900-3935-11ea-96c8-0422402dc106.png)

**Additional context**
The version 2.0.0-beta.6 of allure-js-commons has been tested and it also happens.

**Comment by ehilinger** [comment]
[Test Exploratory Allure Reporter (v.1.1_54 (Last Version).docx](https://github.com/systelab/allure-reporter/files/4852013/Test.Exploratory.Allure.Reporter.v.1.1_54.Last.Version.docx)

**Comment by ManelMoreno** [comment]
The verification done by Jordi Cela, EstherH and Marco demostrated that this issue is solved.
(A new one appeared, at a deeper level, but it will be reported in a different issue.
