### ISSUE TITLE
Report button is not disabled if the fields are not informed (it was in 1.0). 

### ISSUE THREAD

**Issue by ManelMoreno** [systelab/allure-reporter#64]
Only should be enabled when the required fields are informed: Project, Test Plan, Test Cycle, Test Group, New Test Cycle name (only if Test Cycle is new)
For the new "Update TC" button only is needed to inform the field Project (it should be enabled with only the field project informed)

**Comment by olgapuig** [comment]
It applies to Report and Update TC fields. Each button needs a different case to be enabled.

**Comment by JordiCela** [comment]
Steps to Perform:
1. Open webpage: https://systelab.github.io/allure-reporter-test/
2. Login with your credentials
3. Drop some allure files in the webpage
4. Go to Send the Results to Jama
5. Leave empty all fields
6. Focus on the 'Report' button
7. Enter a value in the 'Project' field
8. Focus on the 'Report' button
9. Enter a value in the 'Test Plan' field
10. Focus on the 'Report' button
11. Enter a value in the 'Test Cycle' field different from 'New Test Cycle'
12. Focus on the 'Report' button

Expected Result:
After performing step 6, the 'Report' button is disabled
After performing step 8, the 'Report' button is disabled
After performing step 10, the 'Report' button is disabled
After performing step 12, the 'Report' button is enabled
