### ISSUE TITLE
Update the link to angular spec in the documentation of the tool and change version to 2.0

### ISSUE THREAD

**Issue by ManelMoreno** [systelab/allure-reporter#65]
The table that appear on the UI documentation is updated but there is a pending link to update:
https://github.com/systelab/seed-angular/blob/master/e2e/login/login.e2e-spec.ts
should be
https://github.com/systelab/seed-angular/blob/master/e2e/login/tests/login.e2e-spec.ts

**Comment by danipiques** [comment]
Additionally, update the version to 2.0
