### ISSUE TITLE
Support the updated libraries (linked with seed-angular)

### ISSUE THREAD

**Issue by olgapuig** [systelab/allure-reporter#68]
In the seed-angular, the Allure libraries will be updated at https://github.com/systelab/seed-angular/issues/51
Ensure Allure-reporter works as intended with the new versions.

**Comment by olgapuig** [comment]
The latest versions are "allure-js-commons": "^1.3.2" and "jasmine-allure-reporter": "^1.0.2". The seed is already up to date.
There is a Beta of allure-js-commons but the strategy is not using beta versions.

**Comment by ManelMoreno** [comment]
@OscarDeDios , @olgapuig do you consider this issue as totally closed further verification/validation is needed? Did you perform some internal checks? In any case, I assume that with the verification for the rest of the issues and final validation, this update will be confirmed as not having impact..

**Comment by olgapuig** [comment]
No change was performed.  The latest versions are "allure-js-commons": "^1.3.2" and "jasmine-allure-reporter": "^1.0.2".  which were included in the validation for Allure-reporterv2.0. We wanted to reject this Issue but it is only possible to Close it.

**Comment by olgapuig** [comment]
Angular 
allure-js-commons: "^1.3.2" --> Same version V1.0 y V2.0
jasmine-allure-reporter: "^1.0.2" --> Same version V1.0 y V2.0
wdio/allure-reporter": "7.16.3" --> New dependency for WDIO

**Comment by ManelMoreno** [comment]
Validation protocol must detail these dependencies and versions: TO DO
