### ISSUE TITLE
Define an order in the Test Cases (Epic, alphabetic)

### ISSUE THREAD

**Issue by olgapuig** [systelab/allure-reporter#7]
It would be better to define an order in the test case (TmsLink) execution, and in the report.
Order: Epic (optional), alphabetic using TmsLink

**Comment by ManelMoreno** [comment]
Could we confirm that this is not more needed after the use of the function that stablish the precedence for each TC?

**Comment by olgapuig** [comment]
This is not a priority for V3.0. It will be assessed for future enhancements.

**Comment by ManelMoreno** [comment]
After v.3.0 this is not more a need/request. We decide to Reject and close it.
