### ISSUE TITLE
Create 2 new repositories to test from Angular and Jee 

### ISSUE THREAD

**Issue by olgapuig** [systelab/allure-reporter#71]
https://github.com/systelab/seed-angular/blob/allure-validation/e2e/allure/val.e2e-spec.ts
https://github.com/systelab/seed-jee/blob/allure-validation/src/test/java/com/systelab/seed/allure/AllureValidationTest.java

**Comment by olgapuig** [comment]
The 2 new repositories are created:
- https://github.com/systelab/allure-reporter-test-angular
- https://github.com/systelab/allure-reporter-test-jee

**Comment by ManelMoreno** [comment]
To consider this issue as Done, it is needed to execute both repositories to check that all is executed without problems.

**Comment by atzurk** [comment]
Created the following Pull-Requests:
https://github.com/systelab/allure-reporter-test-jee/pull/3
https://github.com/systelab/allure-reporter-test-angular/pull/3

**Comment by atzurk** [comment]
Received approval to both pull-request from @JordiCela (thanks!!). Repos merged and updated!
