### ISSUE TITLE
User uploading TC steps to JAMA needs more feedback about upload done ('Update TC' button)

### ISSUE THREAD

**Issue by ManelMoreno** [systelab/allure-reporter#72]
(This issue is 'cloned' from #53  , but in this case refered just to the action 'Update Test Case')

When users upload test steps to JAMA they needed to receive feedback about:

Upload is in progress
Upload has finished (all Test Cases have been uploaded)
How many Test Cases (optionally how many Test steps) have been uploaded and how many were not (if possible provide information about the failure cause: TC not found / matched; communication failure; Wrong content....)

**Comment by SCoboG** [comment]
Defect retested with an exploratory Test. The result of the testing has been PASS

The following scenario have been tested:
--------- Upload is in progress ----------------------
- The amount of test cases used for this test has been 58

----------Upload has finished ------------------------
- Upload a total of 12 test cases results with several test steps and substeps:

Scenario 1) All PASS
Scenario 2) Some FAIL
Scenario 3) Some of them not match

See the evidences attached
![Scenario2b](https://user-images.githubusercontent.com/48992378/171805236-026e9b31-e58f-4118-94fe-15f96f02cf99.PNG)
![Scenario3](https://user-images.githubusercontent.com/48992378/171805239-98296bf8-aee1-467e-8c3e-e12a4dcb666c.PNG)
![Upload a total of 12_with 3 fail_KO](https://user-images.githubusercontent.com/48992378/171805241-f13262c1-dc42-4ab6-9c26-c9ee1c703761.PNG)
![Scenario2](https://user-images.githubusercontent.com/48992378/171805243-a1f6595b-1f28-463c-b018-ad109d73c821.PNG)
![Scenario2_Jama](https://user-images.githubusercontent.com/48992378/171805245-6215f74f-d389-45b1-9471-5d6c326fefca.PNG)
[json files for Scenarios.zip](https://github.com/systelab/allure-reporter/files/8830312/json.files.for.Scenarios.zip)
