### ISSUE TITLE
Reporting of 'Last Executed version' value for Test Cases

### ISSUE THREAD

**Issue by ManelMoreno** [systelab/allure-reporter#73]
(Attention: This item is very close related to #51 )

As explained in #51 , the upload of results shall be improved with the version where the test have been executed; but it refers just to Test Run item. This same value should be set to the field 'Last Tested Version' of the Test Case corresponding to each Test Run where a result is being set.
The values to be set are a closed enumerated list already defined in JAMA for each project. P.ex.: see this example:
![image](https://user-images.githubusercontent.com/42932104/123808584-2dad9280-d8f1-11eb-86e7-0f9fc7a07268.png)

So the implementation of this request must take into account the implementation of #51 because each time a result is uploaded to a Test Run, using a release value, this same value must be used to set it on the according Test Case.

**BUT THERE IS AN EXCEPTION FOR THE PREVIOUS GENERAL RULE:** when I execute test runs for a HF, patch, SP or Cybersecurity patch Validation OVER an OLDER version (different from the current in development) I DO NOT WANT TCs to be updated with the label of the old version. 

So the implementation of this request shall allow to **optionally set release to TCs when setting releases for Test Runs,** using the most adequate UI controls.

As a wish, the feedback informing about the upload of results, could also mention the Test Cases modification, in some manner)

**Comment by ainhoam** [comment]
![last test in version](https://user-images.githubusercontent.com/2478494/165918740-e84d2608-e7c8-4c9e-9504-3495ab40a9d6.PNG)
The field "last tested in version" is upload.
