### ISSUE TITLE
Add feedback to the file dropping feature

### ISSUE THREAD

**Issue by OscarDeDios** [systelab/allure-reporter#76]
Dropping files to upload could be slow when there are many. To know if all files have been processed and open the Jama report dialog, you have to see the tables and wait until the numbers don't change anymore.

It could be better to have a progress bar to know how many files have been processed and how many are missing.

**Comment by OscarDeDios** [comment]
Solution proposed in the PR:

![image](https://user-images.githubusercontent.com/722614/132735935-c8920425-05c2-4c13-a8ed-a27e9ce0fa7b.png)



https://user-images.githubusercontent.com/722614/132667747-fa51dd9d-ec93-4e06-836e-adc54c6b00e0.mp4

**Comment by ManelMoreno** [comment]
@ainhoam : talking with dev.team they inform that jus a UI component has changed with no functional impact.
You can re-test the visual part of this issue.
