### ISSUE TITLE
Defect using 'Update Test Case' option: data in other fields are deleted

### ISSUE THREAD

**Issue by ManelMoreno** [systelab/allure-reporter#83]
When the user does the 'Update Test Case' option, in order to update the Description and the Steps to a Test Case in JAMA, other fields than the expected ones **are affected being deleted.** 
In the case detected 'Test Design Status' and 'Last Tested Version' values are removed (see image attached). This is not expected at all.

**This error blocks the use of this feature.**

1. Go to Allure Reporter v.2.0
2. Drop a jason or xml with a TC result existing in JAMA, with values on all TC fields.
3. Log in JAMA and Click on 'Update Test Case'.
4. Go to JAMA to check that the TC has the uploaded Description and Steps and See that values in other fields have been deleted by error
![UpdateSteps_error](https://user-images.githubusercontent.com/42932104/143207770-aea2f569-dc5f-442a-9dd7-da9d74f9ec43.png)
.
Note: You probably will not see this error using the item 'Test Case (IL)', as it does not use the deleted fields mentioned here.

**Comment by olgapuig** [comment]
![MicrosoftTeams-image (45)](https://user-images.githubusercontent.com/1970034/143549721-1f52368e-343d-4ff1-a292-c273e4289b89.png)

**Comment by ManelMoreno** [comment]
After evaluation, we have consider that the best way to address this issue would be changing the way the item is being updated. It is just needed to update the fields 'Description' and 'Steps', regardless the presence or values of any other field.

**Comment by SCoboG** [comment]
Defect retested with an exploratory Test. The result of the testing has been **PASS**

See the evidences attached
[Evidences item #83.zip](https://github.com/systelab/allure-reporter/files/8609549/Evidences.item.83.zip)
:

**Comment by ManelMoreno** [comment]
@danipiques Are you waiting the fix of the other two to include this one in a regression? Susana set the exploratory to Pass, so we should trust it is correcltly fixed.

**Comment by danipiques** [comment]
Hello @ManelMoreno , I'm going to check it with @SCoboG. Thanks!

**Comment by danipiques** [comment]
Verified, in Allure 3.0 only the description and the steps are updated with the action "Update test case" on the element "Test Case" (see evidence)
![Allure #83](https://user-images.githubusercontent.com/40574863/188838731-b8e9fb18-120b-42fa-a73c-5fd0a3bee6a5.png)
